### ISSUE TITLE
A fix for the gb-gangs resource download

### ISSUE THREAD

**Issue by sinfuljosh** [qbcore-framework/txAdminRecipe#10]
The URL is incorrect for the qb-gangs resource. You can also add subpath to address the directory issue. 
Old:
https://github.com/qbcore-framework/txAdminRecipe/blob/56cde1e8f93abc1156b51614b4cc75b61a4808e8/qbcore.yaml#L73-L76

New: 
```
  - action: download_github
    dest: ./resources/[qb]/qb-gangs
    subpath: qb-gangs
    ref: main
    src: https://github.com/Mojito-Fivem/qb-gangs
```

And remove lines 490-504. 
https://github.com/qbcore-framework/txAdminRecipe/blob/56cde1e8f93abc1156b51614b4cc75b61a4808e8/qbcore.yaml#L490-L504

**Comment by BerkieBb** [comment]
You could better make a pull request on this but thanks for the heads up!
