### ISSUE TITLE
Properties app - click on keys

### ISSUE THREAD

**Issue by wanderrer** [qbcore-framework/txAdminRecipe#100]
It will throw an error: SCRIPT ERROR: @npwd_qb_housing/server/server.lua:38: No such export getKeyHolderData in resource qb-houses

**Comment by ansljeremy** [comment]
This issue should be created in the [npwd_qb_housing](https://github.com/npwd-community/npwd_qb_housing) repo.

**Comment by SamShanks1** [comment]
update your qb-housing
