### ISSUE TITLE
this is weird, when you see it, you will never unsee it.

### ISSUE THREAD

**Issue by DooubleTap** [qbcore-framework/txAdminRecipe#111]
This is the default txadmin latest qbcore install, and there is a > in the screen. 
![image](https://github.com/qbcore-framework/txAdminRecipe/assets/3772136/f97b6424-1d90-4b09-9ea2-65dfceac27b7)
Am i high ? :D

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-banking/commit/d0aa06dee2a4154b7aca7c5e4cd620e4b8619644
