### ISSUE TITLE
[ERROR] SQL

### ISSUE THREAD

**Issue by CxCore-xyz** [qbcore-framework/txAdminRecipe#129]
When i try to install the recipe via txadmin i get error with sql and then the recipe installing ends and can't install it

bank_accounts
  `users` longtext DEFAULT '[]',

**Comment by GhzGarage** [comment]
Does this work for you? https://github.com/qbcore-framework/txAdminRecipe/pull/130/commits/30c56cccdce06b543b867e8564a52534a615847a

**Comment by HELONERO** [comment]
Same issue

**Comment by HELONERO** [comment]
> Does this work for you? [30c56cc](https://github.com/qbcore-framework/txAdminRecipe/commit/30c56cccdce06b543b867e8564a52534a615847a)

yes this working

**Comment by mirajehossain** [comment]
> Does this work for you? [30c56cc](https://github.com/qbcore-framework/txAdminRecipe/commit/30c56cccdce06b543b867e8564a52534a615847a)
@GhzGarage It's working! I'm curious why this hasn't been merged into the main branch yet.

**Comment by GhzGarage** [comment]
Just pushed the fix for it sorry for the delay
