### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by Pintta** [qbcore-framework/txAdminRecipe#137]
CREATE TABLE IF NOT EXISTS `bank_accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `citizenid` varchar(11) DEFAULT NULL,
  `account_name` varchar(50) DEFAULT NULL,
  `account_balance` int(11) NOT NULL DEFAULT 0,
  `account_type` enum('shared','job','gang') NOT NULL,
  `users` longtext DEFAULT '[]',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `account_name` (`account_name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

BLOB, TEXT, GEOMETRY or JSON column 'users' can't have a default value

**Comment by GhzGarage** [comment]
Just pushed the fix for it sorry for the delay
