### ISSUE TITLE
download error message

### ISSUE THREAD

**Issue by linksanco** [qbcore-framework/txAdminRecipe#138]
you cannot create when you download your files, it comes with an error htrough tx admin

Builds - fivem/build_server_windows/master/[8389]
 
https://imgur.com/T89oBxF

https://imgur.com/pyaOVMu

**Comment by linksanco** [comment]
> you cannot create when you download your files, it comes with an error htrough tx admin
> 
> https://imgur.com/T89oBxF
https://imgur.com/pyaOVMu

**Comment by t0r3tto** [comment]
> This error happens when your IP address was blocked by the GitHub servers for sending too many requests, which happens mostly when using a shared hosting where many servers are on the same IP Address.
