### ISSUE TITLE
mysql-async missing in yaml recipe

### ISSUE THREAD

**Issue by dbiegunski** [qbcore-framework/txAdminRecipe#2]
[    c-scripting-core] Failed to load script @mysql-async/lib/MySQL.lua.
[     script:dpemotes] Error loading script Server/Server.lua in resource dpemotes: @dpemotes/Server/Server.lua:22: attempt to index a nil value (global 'MySQL')

**Comment by BerkieBb** [comment]
It is not missing, qb-core uses ghmattimysql, I updated dpemotes to use ghmattimysql but I need it in the recipe still

**Comment by GhzGarage** [comment]
Been fixed
