### ISSUE TITLE
Database Upload Problem (Bug?)

### ISSUE THREAD

**Issue by ChrisLenga** [qbcore-framework/txAdminRecipe#20]
Encountering the following issue during the recipe install process. 

![image](https://user-images.githubusercontent.com/15137702/130190205-ea1ec1de-8a40-456e-a9a9-f13024a56e25.png)

And on the database side, it's definitely installing some but stopping in its tracks. 

![image](https://user-images.githubusercontent.com/15137702/130190547-f8433532-5c40-460e-975b-e37d638c9f20.png)

The exact part of the sql file is the problem. 

CREATE TABLE IF NOT EXISTS `phone_tweets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `citizenid` varchar(50) DEFAULT NULL,
  `sender` varchar(50) DEFAULT NULL,
  `message` text DEFAULT NULL,
  `date` timestamp NOT DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `citizenid` (`citizenid`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

This appears to be the solution. Note that the dateline has changed to a more flexible manner. 

CREATE TABLE IF NOT EXISTS `phone_tweets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `citizenid` varchar(50) DEFAULT NULL,
  `sender` varchar(50) DEFAULT NULL,
  `message` text DEFAULT NULL,
  `date` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `citizenid` (`citizenid`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

I will continue running some testing on this, but it allowed me to import it accordingly.

**Comment by GhzGarage** [comment]
To be honest we are actually moving to a json twitter file instead of using the database so that is being removed

**Comment by ChrisLenga** [comment]
> To be honest we are actually moving to a json twitter file instead of using the database so that is being removed

This is great, but at least this will solve some situations presently where others may be unable to install via the recipe.
