### ISSUE TITLE
Error when starting the server after using recipe 

### ISSUE THREAD

**Issue by Jackster-2233** [qbcore-framework/txAdminRecipe#48]
When loading the server I get the errors you can see in the image provided which never happened on the old build
![qbissue](https://user-images.githubusercontent.com/68924906/139684095-c7e3874b-32bf-4a96-bc1c-812040a1cc2e.PNG)
s

**Comment by zfbx** [comment]
wait no, you just need to use onesync

**Comment by Jackster-2233** [comment]
> wait no, you just need to use onesync

I am using onesync

**Comment by zfbx** [comment]
legacy? if so that's not onesync. the log at the top says it can't find onesync meaning it's not running

**Comment by zfbx** [comment]
add `set onesync on` to the top of your main .cfg

**Comment by Jackster-2233** [comment]
> add `set onesync on` to the top of your main .cfg

Cheers dude, updated the Artifact and set that seems to have done the trick

**Comment by Jackster-2233** [comment]
![image_2021-11-01_141519](https://user-images.githubusercontent.com/68924906/139685934-ef49807c-a98b-4cb6-b976-f7bd47c9896c.png)

Still getting this

**Comment by zfbx** [comment]
fivem server artifact version?

**Comment by Jackster-2233** [comment]
4394 is the version and see I have onesync set
![image_2021-11-01_141842](https://user-images.githubusercontent.com/68924906/139686386-c01cbfad-9a20-4a15-b572-b68f5bfa2ee4.png)

**Comment by zfbx** [comment]
https://github.com/AvarianKnight/pma-voice/commit/0a4dc5c1a7d6a59af3011907f979ee4c439d0490 according to this you might need 4837 or higher

**Comment by Jackster-2233** [comment]
> [AvarianKnight/pma-voice@0a4dc5c](https://github.com/AvarianKnight/pma-voice/commit/0a4dc5c1a7d6a59af3011907f979ee4c439d0490) according to this you might need 4837 or higher

Thanks dude, all working. Appreciate the help :)
