### ISSUE TITLE
Invalid YAML

### ISSUE THREAD

**Issue by BlutwurstPro** [qbcore-framework/txAdminRecipe#7]
Hey,

i tried to deploy the server via the recipe. But when i clock "Next" at Step 1 it says that the YAML in invalid.
![2021-07-21 20_52_11-Window](https://user-images.githubusercontent.com/10463210/126544103-41d760b5-9880-4f0e-863e-3fbbd36a6749.png)

**Comment by gobboo** [comment]
^ Same issue

**Comment by gobboo** [comment]
Found a fix, when using the URL it seems to break the indentation

https://raw.githubusercontent.com/qbcore-framework/txAdminRecipe/main/qbcore.yaml

Go here and copy then paste it into the "Review Recipe" part of the TXAdmin setup, just

**Comment by Hans691** [comment]
@gobboo Now Working

**Comment by BerkieBb** [comment]
@BlutwurstPro @Hans691 the recipe has been recently updated, can you check if you still have the issue?
